### ISSUE TITLE
Initial Value Empty if initial value is ZERO

### ISSUE THREAD

**Issue by Flavsditz** [kevinongko/vue-numeric#103]
## Expected Behavior
My initial value is Zero. So I expect to see the value Zero formatted the way I configured it. I expect to see the field like this when **I first open the page**:
![image](https://user-images.githubusercontent.com/1968234/116192356-06d6b280-a72e-11eb-8c3a-6f2fa167aa9d.png)

## Actual Behavior
When I first load the page all the values **that are initially zero** are rendered as empty fields:
![image](https://user-images.githubusercontent.com/1968234/116192432-240b8100-a72e-11eb-9542-ea61734b4ac1.png)

If I click on the field then I get a value zero shown and if I click out of the field (blur) then the zero stays there formatted too. However, if I navigate to another page and get back the value is again gone.

This only happens on values that are ZERO. All other values get correctly displayed initially too.
I thought it might have something to do with the default value but that wasn't the case.

I took a look and thought this might be related to  #5 but it seems to be something a bit different.

## Specifications

  - Plugin Version: 4.2.1
  - Vue.js Version: 2.6.11
  - Browser: Chrome
  - OS: Linux

## Code

Here is the component configuration:
```
<vue-numeric
          v-model="ebitdaRate"
          decimal-separator=","
          separator="."
          currency="%"
          currency-symbol-position="suffix"
          :precision="2"
          :minus="true"
          class="growth-rate-input"
        />
```

I am using the vue-class-component so I won't add the component Java code here, but I can guarantee that this is a reactive field which works correctly updating (set and get).

**Comment by Flavsditz** [comment]
Just to give more context:
- I am using Typescript
- I am using [vue-class-component](https://class-component.vuejs.org/)


This code shows an initial value (set to 10)
```
<template>
  <vue-numeric
    v-model="value"
    decimal-separator=","
    separator="."
    currency="%"
    currency-symbol-position="suffix"
    :precision="2"
    :minus="true"
    class="growth-rate-input"
  />
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Overview extends Vue {
  value = 10;
}
</script>

<style scoped lang="scss"></style>
```

This code **DOES NOT** show an initial value (set to 0)
```
<template>
  <vue-numeric
    v-model="value"
    decimal-separator=","
    separator="."
    currency="%"
    currency-symbol-position="suffix"
    :precision="2"
    :minus="true"
    class="growth-rate-input"
  />
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Overview extends Vue {
  value = 0;
}
</script>

<style scoped lang="scss"></style>
```

**Comment by eboye** [comment]
I encountered the same problem. Any solution to this?

**Comment by eboye** [comment]
I've "fixed" it by setting the value to 0.000000001, but am really hoping that this is going to be fixed.

**Comment by Flavsditz** [comment]
That would not be a good solution for me since I am dealing with big numbers and this would cause differences in values :/

**Comment by eboye** [comment]
I'm also experiencing this, but as steps for me are 0.01 I do check if the values is < 0.001 then I set it to 0. It's a nasty hack, but works for me.

**Comment by Flavsditz** [comment]
Ok I took a couple of minutes today and checked the reason why this happens.

It has to do with the fact that in javascript the value `0`  is considered false. ( A bit more info here: https://www.geeksforgeeks.org/why-0-is-equal-to-false-in-javascript/)
It has to do that the **numeric** representation of `true` and `false` is `1` and `0` respectively.

So the line 278 where the mounted function checked for a value:
```js
  mounted () {
    // Set default value props when valueNumber has some value
    if (this.valueNumber) {
      this.process(this.valueNumber)
```

was of course never going in.
I fixed by checking if the value is zero if the initial check failed:
```js
  mounted () {
    // Set default value props when valueNumber has some value
    if (this.valueNumber  || this.valueNumber === 0) {
      this.process(this.valueNumber)
```

This fixes the problem. I also added a test so it is covered on the test cases.
I will submit a PR in a bit...

**Comment by Flavsditz** [comment]
If the PR gets merged I will close this discussion

**Comment by Flavsditz** [comment]
@eboye I had to add another conditional: `this.valueNumber === 0 && this.value !== ''` or else it would fail another case where we wanted the default value to be empty.

If you need more info just check the PR or ask me

**Comment by genughaben** [comment]
Good day,
I totally need that, too. 
Would really be a great help, if that could be merged! 
Thank you so much for all your effort!
Have a great day!

**Comment by kevinongko** [comment]
Added the fix in 2.4.2, thanks for the input guys, sorry for the slow response
https://github.com/kevinongko/vue-numeric/releases/tag/v2.4.2

**Comment by eboye** [comment]
Great, thanks!

**Comment by amchconsult** [comment]
If I use unpkg or jsdelivr is not applying v2.4.2 with the fix.
Do you know why?
thank you
