### ISSUE TITLE
unpkg or jsdelivr not version 2.4.2

### ISSUE THREAD

**Issue by amchconsult** [kevinongko/vue-numeric#108]
If I use unpkg or jsdelivr is not applying v2.4.2 with the fix.
Do you know why? Can you please compile?
thank you

**Comment by kevinongko** [comment]
anything wrong with this link?
https://unpkg.com/vue-numeric@2.4.2/dist/vue-numeric.min.js
https://cdn.jsdelivr.net/npm/vue-numeric@2.4.2

**Comment by kevinongko** [comment]
I just rebuild and republish 2.4.3, please try again
https://unpkg.com/vue-numeric@2.4.3/dist/vue-numeric.min.js
https://cdn.jsdelivr.net/npm/vue-numeric@2.4.3

**Comment by amchconsult** [comment]
it works perfect now.
before it was not showing zero.
thank you very much
