### ISSUE TITLE
Demo input clipped

### ISSUE THREAD

**Issue by sandervanhooft** [kevinongko/vue-numeric#11]
On the [demo page](https://kevinongko.github.io/vue-numeric/), the field gets clipped vertically.
![img_2080](https://cloud.githubusercontent.com/assets/7265703/26775493/82e20dd0-49d5-11e7-8faf-94eee28672ec.PNG)

The screenshot is from Safari, iPhone 5S, latest iOS. I'm experiencing the same on Safari on my iPad Air. Zoom is 100% (normal).

**Comment by kevinongko** [comment]
Hi @sandervanhooft ,

Thanks for the info, should be fixed now.

**Comment by sandervanhooft** [comment]
Correct, thanks! :)
