### ISSUE TITLE
Allow 0 as Input

### ISSUE THREAD

**Issue by robinrossow** [kevinongko/vue-numeric#117]
Hey, thanks for the nice library. 

I can't seem to figure out how to actually have 0 as the v-model value when I'm initially loading my form.  
The input is just an empty string but it will display the 0 value correctly once I've blurred it. 

This behavior messes with my validation since it won't allow an empty string but will allow a 0.

Is there any way to correctly display the 0 when loading the input? Thanks!

**Comment by kevinongko** [comment]
Hi @robinrossow ,

This is very possible, you can try changing this value in the docs to zero and re-open the html, the value will be zero by default
![image](https://user-images.githubusercontent.com/15880638/145133485-1ae831cc-4d7d-4f18-a727-f4ae100c858b.png)
Sorry for the late reply 😄

**Comment by kevinongko** [comment]
Should be fixed in 2.5.0
please try again
