### ISSUE TITLE
Currency symbol position

### ISSUE THREAD

**Issue by knagyorg** [kevinongko/vue-numeric#15]
Hi, I've made a changes for currency symbol position (some currencies are on the left side, some on the right side). May I do a "Pull request" for your approval?
Karel

**Comment by kevinongko** [comment]
Hi @knagyorg ,

That's cool, go ahead 👍

**Comment by knagyorg** [comment]
Permission to kevinongko/vue-numeric.git denied to knagyorg
Can you grant me access to push?

**Comment by kevinongko** [comment]
submit the PR, i will review and merge it later

**Comment by kevinongko** [comment]
Merged #16, thanks
