### ISSUE TITLE
Support decimals points

### ISSUE THREAD

**Issue by DannyFeliz** [kevinongko/vue-numeric#2]
Hi @kevinongko I really love this component but as you can image if you are working with a field of price  probably you will need to support decimals points and make it configurable (the number of decimals allowed) because at this moment with component only works with integers.

I would like something like this:
```vue
<vue-numeric currency="$" separator="," decimals=2 v-model="price"></vue-numeric>
```

My issue right now is that I want to type `11.99` but I get `1,199`

Cheers

**Comment by kevinongko** [comment]
Thank you for the suggestion, I just updated the components to support decimals 9ea649b4b0c7e369be3bf36041b0e49f6685377c

```vue
<vue-numeric currency="$" separator="," precision="2" v-model="price"></vue-numeric>
```
