### ISSUE TITLE
Expose formatToNumber method for external use

### ISSUE THREAD

**Issue by ankurk91** [kevinongko/vue-numeric#21]
Hi,
Thanks for the great plugin.

Some time we need to show amount on view like
```js
// wants formatted amount
{{product.amount}} 
```
How difficult it is to expose your `formatToNumber` method so that we can import it like :
```js
import format from 'vue-numeric/src/formatter.js'
console.log(format(product.amount,'$'));
// $ 123.25
```
Possibly extract that to a new js file, so that this component can still use it.

This way user no need to install another library to format amounts.
Thanks.

**Comment by kevinongko** [comment]
Hi @ankurk91,

you could use the `read-only` props to show formatted value without the input field

**Comment by ankurk91** [comment]
Oh, cool
I didn't notice that.
Thanks again.
