### ISSUE TITLE
Add ability to customize formatting string

### ISSUE THREAD

**Issue by darrylhein** [kevinongko/vue-numeric#22]
I'm trying to show the input without a currency symbol in it, which works, but a space is always added in front of the number, as far as I can tell, because of the `formatString` computed property.

My 2 ideas are:

1. Change the `formatString` to a prop and add a default value (a function) – possibly the most flexible in the long run.
2. Check if there's a currency and if not, only include the `%v` in `formatString` – probably easiest to implement.

It's probably doable to implement both.

I'm okay to take an attempt at adding this if it's wanted.

Good idea? Bad idea?

**Comment by kevinongko** [comment]
Hi @darrylhein,

Thanks for the suggestion, I implemented idea no 2 in v1.6.2
IMO I didn't found (yet) other use cases for the first idea by adding new `props`, CMIIW
