### ISSUE TITLE
[Feature request] Clear input on focus when value is zero

### ISSUE THREAD

**Issue by ankurk91** [kevinongko/vue-numeric#26]
Hi,

When current value is zero `0.00` and user focus on input, user has to remove this value by pressing backspace 4 times and then he can start typing new values.
It would be good if component can clear the input field automatically when value is zero.

I made a simple directive to achieve this.
```js
Vue.directive('clear-zero', {
  bind: function (el, binding, vnode) {
    el.onfocus = function () {
      if (parseFloat(el.value) === 0) {
        console.log('Clear value');
        el.value = null;
      }
    };
  }
});
```
```html
<vue-numeric v-clear-zero currency="$" :precision="2" v-model="amount ></vue-numeric>
```

**Current behavior**
![vue-numeric-issue](https://user-images.githubusercontent.com/6111524/29995539-38ae217a-9009-11e7-9da7-d07c80b2cfd1.gif)
**Expected behavior (with directive)**
![directive](https://user-images.githubusercontent.com/6111524/29995544-4a443e06-9009-11e7-91ae-1d320fbf3395.gif)

**Comment by kevinongko** [comment]
Thanks, this behavior is fixed in v2.0.0
