### ISSUE TITLE
[2.0.0] No longer working

### ISSUE THREAD

**Issue by ankurk91** [kevinongko/vue-numeric#27]
Hi,
just updated to v2.0.0 found issue.

Component does not accept new valid values on blur event.
https://jsfiddle.net/acvr9byw/

**Steps to reproduce**
* Setup  a component with `null` value
`<vue-numeric currency="$" precision="2" v-model="price"></vue-numeric>`
* Type in input some value eg - `5566`
* Click outside of input
* Input value remains 0.00
![vue-numeric-v2](https://user-images.githubusercontent.com/6111524/30001157-cabf4226-90a2-11e7-9c3e-e801f1ce57f7.gif)

**Comment by kevinongko** [comment]
Sorry, fixed in 2.0.1

Thanks for the report @ankurk91

**Comment by menezesbr** [comment]
Good evening. Now in version 2.1.2 the problem of zeroing has returned

**Comment by kevinongko** [comment]
Hi @menezesbr,
Could you give more details steps how to reproduce the problem? Thanks
