### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by gustavobissolli** [kevinongko/vue-numeric#3]

**Comment by kevinongko** [comment]
Hello @gustavobissolli , can you give me more information what doesn't work? thank you

**Comment by gustavobissolli** [comment]
Sure kevin!! I am going to check better!

I was really tired after a lot of time working directly hahahaha...

If I still have problem I'll tell you!

**Comment by kevinongko** [comment]
I'll close this issue this issue for now, feel free to open new issue if you found any problem :)
