### ISSUE TITLE
version 2.1.1 problem prop read-only="true"

### ISSUE THREAD

**Issue by cuautorres** [kevinongko/vue-numeric#30]
when the read-only property is set to true, the value of the v-model is not displayed

**Comment by kevinongko** [comment]
Hi @cuautorres, could you show me your code in [jsbin](http://jsbin.com/)?

**Comment by kevinongko** [comment]
I'm closing this because inactivity, the read-only props is working correctly in the demo. Feel free to reopen this issue and provide sample code before I can check what's wrong.

This is just a guess, make sure to use `v-bind` so your true value is boolean and not string.
