### ISSUE TITLE
Vue-numeric on change event not working!

### ISSUE THREAD

**Issue by Datta-Telukunta** [kevinongko/vue-numeric#34]
checkdata function is not getting triggered when I change the value, please suggest?

<vue-numeric class="form-control"
                         v-clear-zero
                         currency="$"
                         :precision="2"
                         :min="0"
                         v-on:change = "checkdata()"
                         :name="`current-balance`"
                         v-model.number="currentBalance"
            ></vue-numeric>

**Comment by kevinongko** [comment]
Hi @Datta-Telukunta,

I just checked the demo and it's working fine.
Can you give more specific steps to reproduce? preferably in jsbin.com, Thanks

**Comment by Datta-Telukunta** [comment]
`<vue-numeric class="form-control"
                         v-clear-zero
                         currency="$"
                         :precision="2"
                         :min="0"
                         v-on:change = "checkdata()"
                         :name="`current-balance`"
                         v-model.number="currentBalance"
            ></vue-numeric>`

**Comment by kevinongko** [comment]
- what does this `checkdata()` function do?

**Comment by Datta-Telukunta** [comment]
Thanks @kevinongko 
It is working now. In  `checkdata()` function I am changing some model values. `v-clear-zero` custom directive.
