### ISSUE TITLE
Vue-numeric DOM doesn't update?

### ISSUE THREAD

**Issue by Diathedia** [kevinongko/vue-numeric#39]
Excuse me, thank you for the plugin.

I made a dynamic number entry and saved it into the database. However when I loaded the value from database and pushed the array to render in the dom (using v-for), the vue-numeric doesn't update (needs to be clicked first to update)

## Expected Behavior
When model is programatically updated, updates dom and formats it

## Actual Behavior
Shows placeholder instead
![screen shot 2017-10-19 at 10 57 26](https://user-images.githubusercontent.com/16350116/31753736-b9990dcc-b4bc-11e7-88c9-253a55449ada.png)
After click:
![screen shot 2017-10-19 at 10 57 32](https://user-images.githubusercontent.com/16350116/31753743-c0cefa34-b4bc-11e7-90b7-8a74c8729d12.png)

## Specifications
  - Plugin Version: 2.2.3
  - Vue.js Version: 2.5.2
  - Browser: Google Chrome
  - OS: MacOS Sierra 10.12.6

Sorry for my bad English, and thanks before.

**Comment by kevinongko** [comment]
Hello @Diathedia,

I tried [this](http://jsbin.com/nozorek/3/edit?html,js,output) approach and it's working. 
Could you share your code to reproduce the problem? preferably in jsbin.com

**Comment by Diathedia** [comment]
Sorry for the late reply. Apparently it happens when it's hidden from the dom.
[Here is the code](http://jsbin.com/bequxokoca/edit?html,js,output). Thanks before!

**Comment by kevinongko** [comment]
Oh, that's probably because of how the `placeholder` props works, it will prioritise the placeholder even if there's a value.

**Comment by Diathedia** [comment]
Hmm, [normal input](http://jsbin.com/baqaqacipu/edit?html,js,output) don't behave like that, though. I wonder if there's a way to fix this?

**Comment by kevinongko** [comment]
it doesn't need to be fixed because it's intended to work like that, please open new issue if you have suggestion to change how placeholder props works.

**Comment by mtskf** [comment]
This sounds very odd - "it will prioritise the placeholder even if there's a value."
HTML <input> placeholder attribute doesn't work like this way.
Is there any particular reason why you do this?
