### ISSUE TITLE
Change decimal sepator on enter

### ISSUE THREAD

**Issue by fscardua** [kevinongko/vue-numeric#4]
The component change the decimal separator on enter. 

**To test:**
`<vue-numeric v-bind:precision="2" separator="." v-model="price" placeholder="My price" ></vue-numeric>`

1 - Click on input and put the value 123,43
2 - Take the focus out the component. The masked value is correct.
3 - Click on input and confirm the value 123.43. On enter the decimal separator was changed to "."

**Comment by kevinongko** [comment]
Hi @fscardua , I can't reproduce step 3 because when I press `enter` nothing happen.
But I did found when on focus the decimal become `.` instead of `,`.
I've fix this problem in v1.4.2, hopefully this fix your problem.
Thanks

**Comment by fscardua** [comment]
@kevinongko take a look at this JQuery Plugin 
[https://github.com/plentz/jquery-maskmoney](https://github.com/plentz/jquery-maskmoney)

It would be amazing if your component worked like this plugin. It's just a suggestion .

**Comment by kevinongko** [comment]
Hi @fscardua,

- Default value from v-model should work now in v1.5.0. 
- I don't quite understand about masking problem with decimal comma separator. It works correctly when I tried in [live demo](https://kevinongko.github.io/vue-numeric/), can you give me a demo or more detailed step to reproduce?
- about the jQuery plugin, IMO masking on blur is less distracting than on input.
- if there are any new feature you want to apply for this component, feel free to suggest it by opening new issue or PR, let's keep this topic for bugs only :)
