### ISSUE TITLE
Allowing spaces in seperator

### ISSUE THREAD

**Issue by tjrchampion** [kevinongko/vue-numeric#40]
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

## Expected Behavior
Some currencies do not use a seperator, rather a space, but this plugin enforces either a , or . 
Is there any chance you might support this, or can I contibute to your plugin and make the required amend?

## Actual Behavior
forces use of , or . 

## Steps to Reproduce the Problem

  1. trying to put a space for the seperator. Simply seperator=" "
  
## Specifications

  - Plugin Version: latest
  - Vue.js Version: 2.x
  - Browser: Firefox/Chrome etc.
  - OS: OSX/Windows/Lunix etc.

**Comment by kevinongko** [comment]
Added in v2.2.4
```html
<vue-numeric separator="space"></vue-numeric>
```

**Comment by EndevelCZ** [comment]
I believe that correct  syntax is <vue-numeric separator="'space'"></vue-numeric>

(Single quotes around the value)
