### ISSUE TITLE
Computed value doesn't update field or read-only

### ISSUE THREAD

**Issue by mikestreety** [kevinongko/vue-numeric#41]
Hello!

Thanks for a great plugin. It seems when using a computed value to populate the field, the `amountNumber` variable doesn't get updated. When inspecting the element, I can see the `valueNumber` and `value` get updated correctly. Anything I can do to help - just say!

## Steps to Reproduce the Problem

1. Go to [this codepen](https://codepen.io/mikestreety/pen/aLgMPM)
2. Note how 83.33 is the correct number (`1000 / 12`)
3. Update the first field to `1200`

## Expected Behavior

All fields update to have `100` as their contents

## Actual Behavior

Nothing updates visually, but values do update on the component (note the `value` and `valueNumber` in the screenshot below)

![screen shot 2017-10-25 at 09 48 17](https://user-images.githubusercontent.com/354085/31989563-954810e6-b96a-11e7-9f83-1cbaa452ac0a.png)

## Specifications

  - Plugin Version: 2.2.4
  - Vue.js Version: 2.5.2
  - Browser: All
  - OS: High Sierra

**Comment by kevinongko** [comment]
Hi @mikestreety,

Thanks for the report, should be fixed in v2.2.5

**Comment by mikestreety** [comment]
Absolute legend - thanks @kevinongko!
