### ISSUE TITLE
Model not updated when rendered initially 

### ISSUE THREAD

**Issue by Esslamb** [kevinongko/vue-numeric#5]
On component render, I'm loading optionData from my database which holds the price in a string format. On Initial load the price just doesn't get set, I have to manually click into the field to re-render it for it to pick up the change.
SCRIPT
`  data() {
    return {
      name: '',
      price: ''
    }
  },`
  `props: [
    'optIndex',
    'optionData'
  ],`
  `created() {
    this.name = this.optionData.name;
    this.price = this.optionData.price;
  },`

HTML
`<vue-numeric
        currency="£"
        separator=","
        v-model="price"
        class="form-control"
        placeholder="Price"
        id="price"></vue-numeric>`

RESULT
Empty initially but when I click in the field I get 34523213 then when I click out I get the nice formatted version.

Was just wondering if you had any ideas ?

**Comment by kevinongko** [comment]
Hi @Esslamb,

does it also happen if the price value from `optionData` is in `Number` format?

**Comment by Esslamb** [comment]
Hey @kevinongko,

I did attempt to use an integer value yesterday but that wasn't working for me either it was almost like the DOM wasn't rendering when the value changed but I could see the value with Vue inspector. I downloaded the latest version and that works great thanks for the quick update!!
