### ISSUE TITLE
Support hundreds separators

### ISSUE THREAD

**Issue by groenroos** [kevinongko/vue-numeric#50]
Is there a way to format the number for the [Indian numbering system](https://en.wikipedia.org/wiki/Indian_numbering_system); i.e. "1,00,000" instead of "100,000", or "1,00,00,000" instead of "10,000,000"? It's the only format that makes sense when dealing with values in Indian rupees (and a few other currencies).

**Comment by kevinongko** [comment]
Currently vue-numeric still dependent on `accounting-js` library which doesn't support hundreds separators. I'll look into this feature after refactoring the plugin to drop external lib.

**Comment by groenroos** [comment]
Dropping the dependency sounds like a great solution!

Temporarily, I was able to patch this is by extending the component like so (knowingly downgrading some capabilities I don't need). Turns out, hundred separators can be handled natively in JavaScript!

	import VueNumeric from 'vue-numeric'

	export default {
		extends: VueNumeric,
		name: 'vue-numeric-hundreds',

		methods: {
			format (value) {
				return this.currency + " " + Number(value).toLocaleString('en-IN');
			}
		}
	}

**Comment by kevinongko** [comment]
Currently I have no time to rewrite this, will close this for now
