### ISSUE TITLE
Is `null` as a value possible?

### ISSUE THREAD

**Issue by rathesDot** [kevinongko/vue-numeric#53]
Hey,

is it possible to add `null` as a value?

For a more detailed explanation, this is my scenario:

I have a form which is populated by API data and the user should add/change data and then submit it. There we have a `<vue-numeric>` input as well. When the user edits the field, everything works as expected.

But I have the situation that sometimes the input isn't populated at all and the user doesn't change anything either. In this case the empty value `0` is sent back to the API but it should be `null` ...

I just saw that there is something like `:empty-value` now ... But it still expects the the value is a Number, doesn't it?

**Comment by ReuDa** [comment]
I think this is related to https://github.com/kevinongko/vue-numeric/issues/57

**Comment by rathesDot** [comment]
Yes, there something like an empty-state is missing ... And with it to get back to that empty-state as well.

**Comment by julienmonty** [comment]
Same issue here. Any update ?

**Comment by fergardi** [comment]
This will be absolutely necessary for me as well, +1.

**Comment by zezic** [comment]
Same here. May be merge in this fork: https://github.com/nettix-oy/vue-numeric/tree/nettix-null-empty-value ?

**Comment by felipedgarcia** [comment]
@zezic This fork that you mentioned has what I need but just for integers. For decimals it isn't working yet. :cry: It's also necessary for me.

**Comment by vizcay** [comment]
I'm on the same boat, I need a numeric input with the particularity that 0 should be displayed as emtpy.. I would be able to do that if I can set the input's value to null, but there is no way do it as I can see.

**Comment by Aterr** [comment]
still waiting for it also.

**Comment by egeersoz** [comment]
Same here. Any updates?

**Comment by musman92** [comment]
any update?

**Comment by rathesDot** [comment]
Since there doesn't seem to be any feedback, maybe it is time to create a fork and fix it? In my case, I'm not working on that project anymore, so there is no need for me there.

**Comment by rathesDot** [comment]
Since there does not seem to be any progress on it, I am gonna close this issue. Feel free to re-open it if someone is gonna pick this up and need more input.

**Comment by skironDotNet** [comment]
definitely needed null = empty
