### ISSUE TITLE
vue-numeric + vee-validate

### ISSUE THREAD

**Issue by mdipierro** [kevinongko/vue-numeric#56]
<vue-numeric v-model="test" v-validate="'required'"></vue-numeric> causes a vee-validate  "undefined" error. I understand this is not a vue-numeric bug but would be great if it could support the v-validate attribute of vee-validate.js. Maybe I am using the wrong notation and there is a way to make vee-validate work with vue-numeric, but I could not find it anywhere. I believe it simply needs to propagate the v-validate attribute if present. I can help with testing.

**Comment by kevinongko** [comment]
Hi @mdipierro,

Thanks for the report, however I didn't use `vee-validate`
I'll look into it when I have time, hopefully someone can look into this issue.

**Comment by lelukas** [comment]
`<vue-numeric :name="`max-cache-${index}`"
                                 :id="`max-cache-${index}`"
                                 v-model="freelancer.maxCache"
                                 v-validate="{required: true, min_value: 1}"
                                 currency="R$"
                                 separator="."
                                 type="text"></vue-numeric>`

this code worked with me

**Comment by lelukas** [comment]
![webstorm64_2018-07-25_20-29-42](https://user-images.githubusercontent.com/14317935/43232927-ba437898-9049-11e8-939e-e4fbf8626795.png)

this code worked with me
