### ISSUE TITLE
readonly

### ISSUE THREAD

**Issue by KirkOlson** [kevinongko/vue-numeric#61]
When I use a :readonly ="true" prop on the component I get a Vue tip:

"Prop "readonly" is passed to component <Anonymous>, but the declared prop name is "readOnly". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "read-only" instead of "readOnly"."

If I change the props name to "read-only" however the component turns into a <span> instead of an <input> which is not what I want, because then I lose aligning and other styling attributes.

**Comment by kevinongko** [comment]
Hi @KirkOlson,

as in the [readme](https://github.com/kevinongko/vue-numeric#props), the props is `read-only` not `readonly` or `readOnly` and the props function is to hide the input field and show the text only, if you want to use styling please use `read-only-class` to apply custom class.
