### ISSUE TITLE
Placeholder shown instead of value

### ISSUE THREAD

**Issue by jeroenschieven** [kevinongko/vue-numeric#65]
## Expected Behavior
Given you have the following vue-numeric component:
```
<vue-numeric v-model="value" placeholder="placeholder" />
```

If value is set, I would expect to see the value. Just as described in the documents:

> Input placeholder when empty

## Actual Behavior
When component is mounted, the value is not shown until you click on the input field. The placeholder is shown instead. 

## Steps to Reproduce the Problem

See example in codesandbox: https://codesandbox.io/s/v821j799wl

## Specifications

  - Plugin Version: 2.3.0
  - Vue.js Version: 2.5.2
  - Browser: Firefox Dev. 60.0b12
  - OS: macOS 10.13.3

In #39 you said it was intended to work like this, can you explain the reason for this?

Thanks!

**Comment by mgasparel** [comment]
If you set your value in the `mounted()` event, this works as expected

  ```
mounted() {
    this.numericValue = 500
},
```

**Comment by nixil** [comment]
@mgasparel this doesn't work unless the value of v-model is actually changed.   I think this is still a bug even though I can give a workaround like this. 
```javascript
  mounted () {
    if (this.numericValue) { 
      const _tmp = this.numericValue
      this.numericValue = this.numericValue + 1
      const self = this
      setTimeout( ()=> {
        self.numericValue = _tmp
      }, 30)
    }
  },
```

**Comment by mtskf** [comment]
Same here - very problematic...
https://codesandbox.io/s/2qhsf

**Comment by sorcerdon** [comment]
The issue can be fixed by modifying the source code.
The mounted() method is incorrect.
The fix:

Before:
`mounted() {
            // Set default value props when placeholder undefined.
            if (!this.placeholder) {
                this.process(this.valueNumber)
                this.amount = this.format(this.valueNumber)

                // In case of delayed props value.
                setTimeout(() => {
                    this.process(this.valueNumber)
                    this.amount = this.format(this.valueNumber)
                }, 500)
            }

            // Set read-only span element's class
            //if (this.readonly) this.$refs.readonly.className = this.readonlyClass
        },`

after:
mounted() {
            // Set default value props when placeholder undefined. - FIXED: if there is a valueNumber should be deciding factor not placeholder
            if (this.valueNumber) {
                this.process(this.valueNumber)
                this.amount = this.format(this.valueNumber)

                // In case of delayed props value.
                setTimeout(() => {
                    this.process(this.valueNumber)
                    this.amount = this.format(this.valueNumber)
                }, 500)
            }

            // Set read-only span element's class
            //if (this.readonly) this.$refs.readonly.className = this.readonlyClass
        },

**Comment by kevinongko** [comment]
should be fixed now
https://github.com/kevinongko/vue-numeric/releases/tag/v2.4.1
