### ISSUE TITLE
Prevent default on wrong input instead waiting for onBlur?

### ISSUE THREAD

**Issue by goors** [kevinongko/vue-numeric#69]
Can you replace blur function with some preventDefault function?
For example, you start typing ",,,,," and then you do blur and value is rest. 

If you use wizard for example and have next/prev buttons user will not be able to see that blur function is executed on next step and he will thing that he entered ",,,,," for some value that can n ot be that.

**Comment by goors** [comment]
You can event put in strings like "asdasdasdas" and blur is called after. THat suck. It should be prevented default!

**Comment by kamilzzz** [comment]
@goors You can use @keypress.native="onKeyPress" to prevent inputting incorrect values.
