### ISSUE TITLE
Use development mode in demo

### ISSUE THREAD

**Issue by DojoGeekRA** [kevinongko/vue-numeric#7]
I was browsing your demo page but when i tried to go further with the `vue development tools` i found that it is using production mode or is disabled intentionally:

![captura de pantalla 2017-04-26 a la s 16 02 35](https://cloud.githubusercontent.com/assets/5356595/25456993/4c84bd96-2a9a-11e7-9af5-dce08a3ca476.png)

It will be very helpful for future users if you can use development mode or enable it. This way users can tell for example if the value is stored in the state as raw or masked just checking out the vue tab.

**Comment by kevinongko** [comment]
Hi @DojoGeekRA ,

[Live demo](https://kevinongko.github.io/vue-numeric/)'s devtool is enabled, enjoy :)

**Comment by DojoGeekRA** [comment]
![captura de pantalla 2017-04-27 a la s 02 48 54](https://cloud.githubusercontent.com/assets/5356595/25473188/18849bf6-2af4-11e7-8ec2-06d1b0cda54a.png)

Amazing @kevinongko, thanks 🤘
