### ISSUE TITLE
Is v-model.lazy respected?

### ISSUE THREAD

**Issue by vizcay** [kevinongko/vue-numeric#72]
When I bind an input with v-model.lazy the data on my vue developer tools doesn't gets updated until it loses focus, working as intended.

With v-numeric, after every input it gets syncronized.. is this right?

**Comment by vizcay** [comment]
Okey so after some research I've found that `v-model.lazy` is not intended to work on components (https://github.com/vuejs/vue/issues/5743). I was trying to get a binding on the `change` event of the input, using `.native` is the way to do it: https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components .

**Comment by zaus** [comment]
Link rot --> https://v2.vuejs.org/v2/guide/components-custom-events#Binding-Native-Events-to-Components
