### ISSUE TITLE
precision has incremental value on 8th decimal place

### ISSUE THREAD

**Issue by vincebanzon** [kevinongko/vue-numeric#78]
This issue occurs when we change the precision to 8 or above.
Issue #1:
When I change the precision to greater than or equal to 8, I get an incorrect input.
Expected behavior is: 0.00000000000
but it becomes:          0.00000001000

Issue #2:
And value increments when changed even if it shouldn't.
So if I change the value from 0.000000000001 to 0.000000000002, I get the value of 0.000000020002.
Do it again, and that changes to 0.000000040003.

Issue #3:
Even if you don't change the value but tries edits it, it will still increment. 
e.g. Given the current input is 0.000000040003, remove 3 (the last digit) then type again 3. So it thinks that you changed the values, even though you didn't. It will continue to increment. the value will now be
0.000000060003

## Steps to Reproduce the Problem
To easily replicate the issue, use this link:
https://kevinongko.github.io/vue-numeric/
  1. Visit the website above.
  2. Change the Decimal digits value to: 8
  3. You will immediately notice 1000.00000002 inside the value textfield.
  4. Notice also the value is 1000.00000001
  5. Change any value except the '2'

## Specifications

  - Plugin Version:2.3.0
  - Vue.js Version: 2.9.3
  - Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
  - OS: Windows 10

**Comment by kevinongko** [comment]
Hi @vincebanzon,
Seems like this is a bug with accounting-js lib, the same [issue](https://github.com/openexchangerates/accounting.js/issues/192) can be found here
