### ISSUE TITLE
Does not accept negative values

### ISSUE THREAD

**Issue by vincebanzon** [kevinongko/vue-numeric#80]
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

I would like to be able to input "-1".
But it resolves back to "0" after leaving the component.
Even if I add the property "min='-100'", I would still get "0" after leaving.
I expect it to accept "-1" input.

Here's a sample code.
<vue-numeric :min="-100" v-model="mynumber"></vue-numeric>

**Comment by geri777** [comment]
There is a property to enable negative values:

`<vue-numeric  :minus="true" ...>`

**Comment by vincebanzon** [comment]
I am done with the project, but thank you for letting me know. I might use this next time. @geri777 
I have not tried it yet, but I'll keep this in mind.
