### ISSUE TITLE
Key "Delete" doesn´t set field to empty-value

### ISSUE THREAD

**Issue by WulfP** [kevinongko/vue-numeric#81]
Instead on Tab-out the original value ist restored.

suggested solution:

```javascript
unformat (value) {
  var emptyString = typeof value === 'string' && value === ''
  value = parseFloat(value.replace ? value.replace(",",".") : value)
  const toUnformat = emptyString ? this.emptyValue : value
  return accounting.unformat(toUnformat, this.decimalSeparatorSymbol)
}
```

The condition for empty strings has to be evaluated before value ist changed.
Otherwise an `empty-value` of 0 is evaluated to false.

**Comment by kevinongko** [comment]
Hi @WulfP,
I have no idea what you mean by "Instead on Tab-out the original value ist restored"
Can you make a better explanation?
