### ISSUE TITLE
Input looses focus

### ISSUE THREAD

**Issue by ablishek** [kevinongko/vue-numeric#82]
I just downloaded your component but am getting an issue where the input looses focus on each keypress. So if the user wants to write 100,000 => he/she must type 1, set focus, 0, set focus, 0, set focus, etc. It can be very tiresome. Is there a work around for this?!?

Following is my code:
`                            <vue-numeric separator="," v-model.native="data.item.value"></vue-numeric>
`

**Comment by abhi-cognitivo** [comment]
Fyi I also tried :value but that solves the focus problem, but does not update the value back to the model. And on lost focus changes the number back to the original value.

**Comment by kevinongko** [comment]
Hi @abhi-cognitivo,
Tried inputting value on [demo page](https://kevinongko.github.io/vue-numeric/), I didn't found the input lost focus on each keypress?

**Comment by arselm** [comment]
I downloaded the component today, I am getting the same behaviour described above. Is there a fix or workaround for this issue?

**Comment by kevinongko** [comment]
@arselm can you provide screen recording when the input lost focus? I can input value on demo page without losing focus
