### ISSUE TITLE
Export the function/method from vue-numeric?

### ISSUE THREAD

**Issue by Shu-Ji** [kevinongko/vue-numeric#85]
Will the plugin export some functions/methods that will be used something like this:

```js
import { VueNumeric } from 'vue-numeric'

const data_str = VueNumeric.thousand(10000, separator=',')
// data_str = 10,000
highcharts.show(data_str)
```

Since we would like to use this not only as a vue componet, but also a function to other pure javascript libs.

**Comment by kevinongko** [comment]
Currently I have no plan to update this feature, feel free to raise a PR
