### ISSUE TITLE
v-on:change doesn't work

### ISSUE THREAD

**Issue by TheJester12** [kevinongko/vue-numeric#86]
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

## Expected Behavior
Adding v-on:change doesn't fire function

## Actual Behavior
v-on:change does nothing

## Steps to Reproduce the Problem

  1. Add v-on:change="functionName" to <vue-numeric>, v-on:blur works...

## Specifications

  - Plugin Version: 2.3.0
  - Vue.js Version: 2.5.17
  - Browser: Chrome
  - OS: Mac 10.14.6

**Comment by subtronic** [comment]
https://github.com/kevinongko/vue-numeric/pull/93

**Comment by maartenpaauw** [comment]
It's possible to use `v-on:change.native="functionName"`.

**Comment by kevinongko** [comment]
should work now, https://github.com/kevinongko/vue-numeric/releases/tag/v2.4.1
