### ISSUE TITLE
Remove 0 as default: how?

### ISSUE THREAD

**Issue by Jaspur** [kevinongko/vue-numeric#88]
@kevinongko 

Hi, how can I remove the default 0 as a value when no value is present or the value is null.

**Comment by tryforceful** [comment]
This might be the same issue as in https://github.com/kevinongko/vue-numeric/issues/57

**Comment by Jaspur** [comment]
No it’s not @tryforceful

**Comment by kevinongko** [comment]
this behavior is removed in https://github.com/kevinongko/vue-numeric/releases/tag/v2.4.1
