### ISSUE TITLE
Decimal comma separator wrong value

### ISSUE THREAD

**Issue by ArthurShlain** [kevinongko/vue-numeric#91]
In Russia we use two keyboard layouts.
One with dot key in numpad (EN), second with comma (Local number format)

With `decimal-separator=","` i get wrong result for me:

Type `9.99`, expected `"9,99"` to be displayed and `9.99` as value.

But i get `999,00` displayed and `999` value

https://codepen.io/ArtZ91/pen/ZEGLWry

**Comment by ArthurShlain** [comment]
Related to https://github.com/kevinongko/vue-numeric/issues/64

**Comment by carmeloNET** [comment]
i have a problem might be  similar, when i am  Typing **0.28540193**, expected "**0.2854019**3" to be displayed **0.28540193** as value.

but i get in the value **0.28540194** and in the input **0.28540195**

**Comment by kevinongko** [comment]
duplicate #64
