### ISSUE TITLE
Does not select all when given focus

### ISSUE THREAD

**Issue by whit0489** [kevinongko/vue-numeric#92]
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

## Expected Behavior
When tabbed or mouse clicked into. All of the text is selected

## Actual Behavior
None of the text is selected

## Steps to Reproduce the Problem

  1. Can be seen directly on your demo: https://kevinongko.github.io/vue-numeric/

## Specifications
N/A given it can be seen on the demo on chrome

  - Plugin Version: 
  - Vue.js Version:
  - Browser: 
  - OS:

**Comment by mykhailotarabtsov** [comment]
@whit0489 Hello.
I've faced the same problem (if it a problem).
So I fixed it in a next way:
Please point out for @mousedown.native and @focus events.
**How I use vue-numeric component:**
`<vue-numeric
          v-keypress-number-handle:[inputType]
          :value="value ? value : 0"
          :disabled="disable"
          :readonly="isReadonly"
          :currency="currency"
          :precision="precision"
          :thousand-separator="selectedSeparators.thousands"
          :decimal-separator="selectedSeparators.decimal"
          currency-symbol-position="suffix"
          @mousedown.native="isNumericClicked = true"
          @input="$emit('input', $event)"
          @blur="$emit('blur', $event); isNumericClicked = false"
          @focus="numericFocusHandler">
        </vue-numeric>`

**Method on focus handler:**
`numericFocusHandler (event) {
      if (!this.isNumericClicked) {
        // select the all input value on tab key
        setTimeout(() => {
          event.target.select()
        }, 50)
      }
      this.$emit('focus', event)
    }`
