### ISSUE TITLE
Trying to use vue-numeric input for all currency related fields of my form  

### ISSUE THREAD

**Issue by kalibano** [kevinongko/vue-numeric#96]
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

## Expected Behavior
when I use `<vue-numeric>` multiple times in a form each should  reactively show its own result 
` <vue-numeric
                  separator=","
                  v-bind:max="99999999999999"
                  class="gui-input"
                  v-bind:empty-value="0"
                  v-bind:min="0"
                  v-bind:precision="4"
                  v-model="budget.audit_cost"></vue-numeric>
             <vue-numeric
                  separator=","
                  v-bind:max="99999999999999"
                  class="gui-input"
                  v-bind:empty-value="0"
                  v-bind:min="0"
                  v-bind:precision="4"
                  v-model="budget.others"></vue-numeric>`

## Actual Behavior

but when enter number in first field, result not show but when enter number in second ,first component result also appears .

## Steps to Reproduce the Problem

  1.import VueNumeric from 'vue-numeric' 
  2.Vue.component('vue-numeric',VueNumeric)
3.

## Specifications

  - Plugin Version:2.3.0
  - Vue.js Version:^2.5.17
  - Browser:
  - OS:

**Comment by kevinongko** [comment]
I do not quite understand, can you please make a demo with codesandbox? thank you

**Comment by Flavsditz** [comment]
I think this may be related to my problem #103 .
What  @kalibano  is probably experiencing is that when they click on the second field, the first one gets updated (due to the blur).

@kalibano does this happens with every value or just zero?

**Comment by kalibano** [comment]
> I think this may be related to my problem #103 .
> What @kalibano is probably experiencing is that when they click on the second field, the first one gets updated (due to the blur).
> 
> @kalibano does this happens with every value or just zero?

yes with every values

**Comment by kevinongko** [comment]
#103 is fixed in 2.4.2
please provide a demo if it's still happening

**Comment by KadirFiratFTW** [comment]
it happens when you give a zero value for v-model. When you refresh page it seems empty field until you click on it. Tested on latest version.

**Comment by kevinongko** [comment]
> it happens when you give a zero value for v-model. When you refresh page it seems empty field until you click on it. Tested on latest version.

@KadirFiratFTW Can you try this again with 2.4.3? seems like I forgot to rebuild when publishing 2.4.2 
tried in my machine and it showing zero value when page refreshed
